# Generated by Django 2.2.6 on 2019-12-21 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='id del Post', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(blank=True, upload_to='post_image/%Y/%m/%d')),
                ('content', models.TextField()),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'borrador'), (1, 'publicado')], default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_on'],
            },
        ),
    ]
