# Generated by Django 2.2.6 on 2019-12-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
