# Generated by Django 2.2.6 on 2019-12-22 03:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191221_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='id del comentario', primary_key=True, serialize=False),
        ),
    ]
