# Generated by Django 2.2.6 on 2019-12-25 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='id del mensaje', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('asunto', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
