# Generated by Django 2.2.6 on 2019-12-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191228_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='parent',
        ),
    ]
