# Generated by Django 2.2.6 on 2019-10-09 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191009_0653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['apellido']},
        ),
        migrations.RemoveField(
            model_name='paquetealumno',
            name='sesion',
        ),
        migrations.AddField(
            model_name='sesion',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.PaqueteAlumno'),
        ),
    ]
