# Generated by Django 2.2.6 on 2019-10-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191009_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='total_horas',
        ),
    ]
