# Generated by Django 2.2.6 on 2019-10-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_sesion_total_horas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesion',
            options={'ordering': ['-tiempo_de_inicio']},
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='fecha_de_clase',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='hora_de_inicio',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='hora_de_salida',
        ),
        migrations.AddField(
            model_name='sesion',
            name='tiempo_de_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='tiempo_de_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
