# Generated by Django 2.2.6 on 2019-10-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191010_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasPaquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='alumno',
            options={},
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='nivel_academico',
        ),
        migrations.RemoveField(
            model_name='paquetealumno',
            name='tipo_de_paquete',
        ),
        migrations.AddField(
            model_name='paquetealumno',
            name='nivel_academico',
            field=models.CharField(blank=True, choices=[('k', 'Kinder'), ('p', 'Primaria'), ('s', 'Secundaria'), ('b', 'bachillerato'), ('u', 'universidad')], help_text='Elige el nivel académico del alumno', max_length=1),
        ),
        migrations.AddField(
            model_name='paquetealumno',
            name='status_paquete',
            field=models.CharField(blank=True, choices=[('a', 'Activo'), ('f', 'Finalizado')], help_text='Elige el estado del paquete', max_length=1),
        ),
        migrations.AddField(
            model_name='sesion',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paquetealumno',
            name='horas_paquete',
            field=models.ForeignKey(help_text='Elige el tipo de paquete del alumno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.HorasPaquete'),
        ),
    ]
