# Generated by Django 2.2.6 on 2019-10-10 20:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191010_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete_Inscrito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='id del Paquete', primary_key=True, serialize=False)),
                ('fecha_de_inscripcion', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Activo'), ('f', 'Finalizado')], help_text='Elige el estado del paquete', max_length=1)),
            ],
            options={
                'ordering': ['fecha_de_inscripcion'],
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='nivel_academico',
            field=models.CharField(blank=True, choices=[('k', 'Kinder'), ('p', 'Primaria'), ('s', 'Secundaria'), ('b', 'bachillerato'), ('u', 'universidad')], help_text='Elige el nivel académico del alumno', max_length=1),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Paquete_Inscrito'),
        ),
        migrations.RenameModel(
            old_name='HorasPaquete',
            new_name='Tipo_de_Paquete',
        ),
        migrations.DeleteModel(
            name='PaqueteAlumno',
        ),
        migrations.AddField(
            model_name='paquete_inscrito',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Alumno'),
        ),
        migrations.AddField(
            model_name='paquete_inscrito',
            name='tipo_de_paquete',
            field=models.ForeignKey(help_text='Elige el tipo de paquete del alumno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Tipo_de_Paquete'),
        ),
    ]
