# Generated by Django 2.2.6 on 2019-10-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191010_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete_inscrito',
            name='horas_consumidas',
            field=models.IntegerField(default=0),
        ),
    ]
