# Generated by Django 2.2.6 on 2019-10-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_paquete_inscrito_horas_consumidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete_inscrito',
            name='horas_consumidas',
        ),
        migrations.AddField(
            model_name='paquete_inscrito',
            name='horas_consumidas',
            field=models.ManyToManyField(to='app.Sesion'),
        ),
    ]
