# Generated by Django 2.2.6 on 2019-10-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191010_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete_inscrito',
            name='horas_consumidas',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='alumno',
        ),
        migrations.AddField(
            model_name='paquete_inscrito',
            name='sesiones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Sesion'),
        ),
    ]
