# Generated by Django 2.2.6 on 2019-10-11 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191010_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Alumno'),
        ),
    ]
