# Generated by Django 2.2.6 on 2019-10-11 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_sesion_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='paquete_Inscrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Paquete_Inscrito'),
        ),
    ]
