# Generated by Django 2.2.6 on 2019-10-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_sesion_paquete_inscrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete_inscrito',
            name='sesiones',
        ),
    ]
