# Generated by Django 2.2.6 on 2019-10-11 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_paquete_inscrito_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='alumno',
        ),
        migrations.AddField(
            model_name='paquete_inscrito',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Alumno'),
        ),
    ]
