# Generated by Django 2.2.6 on 2019-10-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20191011_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='paquete_Inscrito',
        ),
        migrations.AddField(
            model_name='sesion',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Alumno'),
        ),
    ]
