# Generated by Django 2.2.6 on 2019-10-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191011_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete_inscrito',
            name='status',
            field=models.CharField(blank=True, choices=[(True, 'Activo'), (False, 'Finalizado')], help_text='Elige el estado del paquete', max_length=1),
        ),
    ]
