# Generated by Django 2.2.6 on 2019-10-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20191011_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paquete_inscrito',
            options={'ordering': ['fecha_de_inscripcion'], 'verbose_name': 'Paquete Inscrito', 'verbose_name_plural': 'Paquetes Inscritos'},
        ),
        migrations.AlterModelOptions(
            name='sesion',
            options={'ordering': ['-tiempo_de_inicio'], 'verbose_name': 'Sesion', 'verbose_name_plural': 'Sesiones'},
        ),
        migrations.AlterModelOptions(
            name='tipo_de_paquete',
            options={'verbose_name': 'Tipo de Paquete', 'verbose_name_plural': 'Tipos de Paquetes'},
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='alumno',
        ),
        migrations.AddField(
            model_name='sesion',
            name='paquete_inscrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Paquete_Inscrito'),
        ),
    ]
