# Generated by Django 2.2.6 on 2019-10-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191011_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete_inscrito',
            name='horas_realizadas',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
