# Generated by Django 2.2.6 on 2019-10-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_paquete_inscrito_horas_realizadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='observaciones',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
