# Generated by Django 2.2.6 on 2019-10-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20191011_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='observaciones',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
