# Generated by Django 2.2.6 on 2019-10-12 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20191011_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete_inscrito',
            name='horas_realizadas',
        ),
        migrations.AlterField(
            model_name='sesion',
            name='paquete_inscrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_consumidas', to='app.Paquete_Inscrito'),
        ),
    ]
