# Generated by Django 2.2.6 on 2019-10-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20191012_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paquete_inscrito',
            options={'ordering': ['alumno__nombre'], 'verbose_name': 'Paquete Inscrito', 'verbose_name_plural': 'Paquetes Inscritos'},
        ),
        migrations.AlterField(
            model_name='paquete_inscrito',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Alumno'),
        ),
        migrations.AlterField(
            model_name='paquete_inscrito',
            name='status',
            field=models.BooleanField(blank=True, choices=[(True, 'Activo'), (False, 'Finalizado')], default=True, help_text='Elige el estado del paquete'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='paquete_inscrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='app.Paquete_Inscrito'),
        ),
    ]
