# Generated by Django 2.2.6 on 2019-10-15 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20191015_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete_inscrito',
            name='horas_consumidas',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
