# Generated by Django 2.2.6 on 2019-10-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_paquete_inscrito_horas_consumidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete_inscrito',
            name='horas_consumidas',
        ),
    ]
