# Generated by Django 2.2.6 on 2019-10-16 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_paquete_inscrito_horas_consumidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete_inscrito',
            name='horas_consumidas',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
