# Generated by Django 2.2.6 on 2019-12-02 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_paquete_inscrito_horas_consumidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='paquete_inscrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='app.Paquete_Inscrito'),
        ),
    ]
