# Generated by Django 2.2.6 on 2019-12-16 05:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20191202_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='id del Alumno', primary_key=True, serialize=False),
        ),
    ]
