# Generated by Django 2.2.6 on 2019-12-20 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='id del Post', primary_key=True, serialize=False),
        ),
    ]
