# Generated by Django 2.2.6 on 2019-12-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_post_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
