# Generated by Django 2.2.6 on 2019-12-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
