# Generated by Django 2.2.6 on 2020-01-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete_inscrito',
            name='busqueda_id',
            field=models.CharField(default='<djan', max_length=100),
        ),
    ]
