# Generated by Django 2.2.6 on 2020-01-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_paquete_inscrito_busqueda_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete_inscrito',
            name='busqueda_id',
        ),
        migrations.AddField(
            model_name='alumno',
            name='busqueda_id',
            field=models.CharField(default='<djan', max_length=100),
        ),
    ]
