# Generated by Django 2.2.6 on 2020-01-03 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20200102_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='busqueda_id',
        ),
    ]
