# Generated by Django 2.2.6 on 2020-01-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20200102_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='busqueda_id',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id',
            field=models.UUIDField(default='41c39', help_text='id del Alumno', primary_key=True, serialize=False),
        ),
    ]
