# Generated by Django 2.2.6 on 2020-01-03 02:02

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20200102_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='search_field',
            field=models.CharField(default=django.db.models.fields.Field.value_to_string, max_length=50),
        ),
    ]
