# Generated by Django 2.2.6 on 2020-01-03 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20200102_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='search_field',
        ),
    ]
