# Generated by Django 2.2.6 on 2020-01-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_remove_alumno_search_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='serach_field',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
