# Generated by Django 2.2.6 on 2020-01-03 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20200102_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='serach_field',
        ),
    ]
