# Generated by Django 2.2.6 on 2020-01-03 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_remove_alumno_serach_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete_inscrito',
            name='horas_restantes',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
