# Generated by Django 2.2.6 on 2020-01-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_paquete_inscrito_horas_restantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='id_search',
            field=models.CharField(default='<djan', max_length=5),
        ),
    ]
