# Generated by Django 2.2.6 on 2020-01-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alumno_id_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='id_search',
            field=models.CharField(default='<django.forms.fields.UUIDField object at 0x7fa57e7b7050>', max_length=100),
        ),
    ]
