# Generated by Django 2.2.6 on 2020-01-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20200105_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id_search',
        ),
    ]
