# Generated by Django 2.2.6 on 2020-01-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_remove_alumno_id_search'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='AlumnoProfile',
        ),
    ]
